export const servicesList = [
    "Bookkeeping",
    "Business Plans",
    "Capital Gains Tax",
    "Cashflow Management",
    "Cloud Accounting",
    "Corporation Tax",
    "Dext",
    "Direct Debits",
    "Employment Law",
    "Making Pensions Simple",
    "Making Tax Digital",
    "Payroll",
    "Property Tax Planning",
    "QuickBooks",
    "R&D Claims and Tax Credit",
    "Registered Office Services",
    "SEIS and EIS",
    "Self Assessment Tax Returns",
    "Share Plans and Incentives",
    "Sponsorship Documentation",
    "Tax Investigations",
    "Tax Planning and Advice",
    "VAT Returns",
    "Year End Accounts"
];
